projects:
  - name: elysia
    translate: true
    upstream:
      repo: elysiajs/documentation
      branch: main
  - name: drizzle
    translate: true
    upstream:
      repo: drizzle-team/drizzle-orm-docs
      branch: main
  - name: vueuse
    translate: true
    upstream:
      repo: vueuse/vueuse
      branch: main
  - name: unocss
    translate: true
    upstream:
      repo: unocss/unocss
      branch: main
  - name: shiki
    translate: true
    upstream:
      repo: shikijs/shiki
      branch: main
  - name: vitest
    translate: false
    upstream:
      repo: vitest-dev/docs-cn
      branch: dev
  - name: umami
    translate: true
    upstream:
      repo: umami-software/website
      branch: master
  - name: astro
    translate: false
    upstream:
      repo: withastro/docs
      branch: main
  - name: nuxt-color-mode
    translate: true
    upstream:
      repo: nuxt-modules/color-mode
      branch: main
  - name: vue
    translate: false
    upstream:
      repo: vuejs-translations/docs-zh-cn
      branch: main
  - name: unjs
    translate: true
    upstream:
      repo: unjs/website
      branch: main
  - name: nitro
    translate: true
    upstream:
      repo: nitrojs/nitro
      branch: v2
  - name: h3
    translate: true
    upstream:
      repo: unjs/h3
      branch: main
  - name: nuxt
    translate: true
    upstream:
      repo: nuxt/nuxt.com
      branch: main
  - name: nuxt-docs
    translate: true
    upstream:
      repo: nuxt/nuxt
      branch: main
  - name: nuxt-examples
    translate: true
    upstream:
      repo: nuxt/examples
      branch: main
  - name: vite
    translate: false
    upstream:
      repo: vitejs/docs-cn
      branch: main
  - name: vitepress
    translate: false
    upstream:
      repo: vuejs/vitepress
      branch: main
  - name: konva
    translate: true
    upstream:
      repo: konvajs/site
      branch: master
  - name: nuxt-i18n
    translate: true
    upstream:
      repo: nuxt-modules/i18n
      branch: main
  - name: deno
    translate: true
    upstream:
      repo: denoland/docs
      branch: main
  - name: tailwindcss
    translate: true
    upstream:
      repo: tailwindlabs/tailwindcss.com
      branch: main
