export const allRepos = [
  {
    name: "elysia",
    type: "translate",
    origin: "zhcndoc/elysia",
    origin_branch: "main",
    upstream: "elysiajs/documentation",
    upstream_branch: "main",
  },
  {
    name: "drizzle",
    type: "translate",
    origin: "zhcndoc/drizzle",
    origin_branch: "main",
    upstream: "drizzle-team/drizzle-orm-docs",
    upstream_branch: "main",
  },
  {
    name: "vueuse",
    type: "translate",
    origin: "zhcndoc/vueuse",
    origin_branch: "main",
    upstream: "vueuse/vueuse",
    upstream_branch: "main",
  },
  {
    name: "unocss",
    type: "translate",
    origin: "zhcndoc/unocss",
    origin_branch: "main",
    upstream: "unocss/unocss",
    upstream_branch: "main",
  },
  {
    name: "shiki",
    type: "translate",
    origin: "zhcndoc/shiki",
    origin_branch: "main",
    upstream: "shikijs/shiki",
    upstream_branch: "main",
  },
  {
    name: "vitest",
    type: "mirror",
    origin: "zhcndoc/vitest",
    origin_branch: "main",
    upstream: "vitest-dev/docs-cn",
    upstream_branch: "dev",
  },
  {
    name: "umami",
    type: "translate",
    origin: "zhcndoc/umami",
    origin_branch: "main",
    upstream: "umami-software/website",
    upstream_branch: "master",
  },
  {
    name: "astro",
    type: "mirror",
    origin: "zhcndoc/astro",
    origin_branch: "main",
    upstream: "withastro/docs",
    upstream_branch: "main",
  },
  {
    name: "nuxt-color-mode",
    type: "translate",
    origin: "zhcndoc/nuxt-color-mode",
    origin_branch: "main",
    upstream: "nuxt-modules/color-mode",
    upstream_branch: "main",
  },
  {
    name: "vue",
    type: "mirror",
    origin: "zhcndoc/vue",
    origin_branch: "main",
    upstream: "vuejs-translations/docs-zh-cn",
    upstream_branch: "main",
  },
  {
    name: "unjs",
    type: "translate",
    origin: "zhcndoc/unjs",
    origin_branch: "main",
    upstream: "unjs/website",
    upstream_branch: "main",
  },
  {
    name: "nitro",
    type: "translate",
    origin: "zhcndoc/nitro",
    origin_branch: "main",
    upstream: "unjs/nitro",
    upstream_branch: "main",
  },
  {
    name: "h3",
    type: "translate",
    origin: "zhcndoc/h3",
    origin_branch: "main",
    upstream: "unjs/h3",
    upstream_branch: "main",
  },
  {
    name: "nuxt",
    type: "translate",
    origin: "zhcndoc/nuxt",
    origin_branch: "main",
    upstream: "nuxt/nuxt.com",
    upstream_branch: "main",
  },
  {
    name: "nuxt-docs",
    type: "translate",
    origin: "zhcndoc/nuxt-docs",
    origin_branch: "main",
    upstream: "nuxt/nuxt",
    upstream_branch: "main",
  },
  {
    name: "nuxt-examples",
    type: "translate",
    origin: "zhcndoc/nuxt-examples",
    origin_branch: "main",
    upstream: "nuxt/examples",
    upstream_branch: "main",
  },
  {
    name: "vite",
    type: "translate",
    origin: "zhcndoc/vite",
    origin_branch: "main",
    upstream: "vitejs/docs-cn",
    upstream_branch: "main",
  },
  {
    name: "vitepress",
    type: "translate",
    origin: "zhcndoc/vitepress",
    origin_branch: "main",
    upstream: "vuejs/vitepress",
    upstream_branch: "main",
  },
];
